#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${SARACLAW_INSTALL_E2E_IMAGE:-${SARACLAW_INSTALL_E2E_IMAGE:-openclaw-install-e2e:local}}"
INSTALL_URL="${SARACLAW_INSTALL_URL:-${SARACLAW_INSTALL_URL:-https://openclaw.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
SARACLAW_E2E_MODELS="${SARACLAW_E2E_MODELS:-${SARACLAW_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e SARACLAW_INSTALL_URL="$INSTALL_URL" \
  -e SARACLAW_INSTALL_TAG="${SARACLAW_INSTALL_TAG:-${SARACLAW_INSTALL_TAG:-latest}}" \
  -e SARACLAW_E2E_MODELS="$SARACLAW_E2E_MODELS" \
  -e SARACLAW_INSTALL_E2E_PREVIOUS="${SARACLAW_INSTALL_E2E_PREVIOUS:-${SARACLAW_INSTALL_E2E_PREVIOUS:-}}" \
  -e SARACLAW_INSTALL_E2E_SKIP_PREVIOUS="${SARACLAW_INSTALL_E2E_SKIP_PREVIOUS:-${SARACLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
